name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to the main branch
  push:
    branches:
      - main # Change this to your main branch name if it's different

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A single job to build and deploy your site
jobs:
  # The 'build' job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact from subfolder
        uses: actions/upload-pages-artifact@v4
        with:
          # Change this to the path of your static site files
          path: 'your-subfolder-name' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
